services:
  samba:
    build:
      context: ./samba
      args:
        SAMBA_USER: ${SAMBA_USER}
        SAMBA_PASS: ${SAMBA_PASS}
    container_name: samba
    ports:
      - "137:137"
      - "138:138"
      - "139:139"
      - "445:445"
    volumes:
      - ./data/share:/share
      - ./data/timemachinebackup:/timemachinebackup
    restart: always
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./data/torrent-config:/config
      - ./data/share/Downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
  cron:
    build:
      context: ./cron
    container_name: cron
    ports:
      - 9990:9990
    volumes:
      - ./data/share/Downloads:/downloads
    restart: always
