services:
  samba:
    build:
      context: ./samba
      args:
        SAMBA_USER: ${SAMBA_USER}
        SAMBA_PASS: ${SAMBA_PASS}
    container_name: samba
    ports:
      - "137:137"
      - "138:138"
      - "139:139"
      - "445:445"
    volumes:
      - ./data/share:/share
      - ./data/timemachinebackup:/timemachinebackup
    restart: always
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./data/torrent-config:/config
      - ./data/share/Downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - ./data/syncthing-config:/config
      - ./data/share/Syncthing:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: always
  organizer:
    build:
      context: ./organizer
    container_name: organizer
    environment:
      - MODEL=${MODEL}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - ./data/share/Downloads:/share/Downloads:ro
      - ./data/share/Organized:/share/Organized
    restart: always
